---
- name: Increase vm.max_map_count.
  shell: sysctl -w vm.max_map_count=262144

- name: Add Docker GPG key.
  apt_key:
    url: "{{ ansible_docker_repo_key }} "
    id: "{{ ansible_docker_repo_key_id }}"

- name: Add Docker repository.
  apt_repository:
    repo: "{{ ansible_docker_repo }}"

- name: Install Docker and dependencies.
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  with_items: "{{ packages}}"

- name: Add user to Docker group.
  user:
    name: "{{ ansible_user }}"
    group: "{{ docker_group }}"

- name: Create Docker service directory.
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  notify: 
    - restart docker

- name: Ensure Docker is running.
  service:
    name: docker
    state: started
    enabled: yes
